[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# git archive에 태그 정보 포함 (배포용 tarball 생성시 유용)
write_to = "aws_finops_tools/_version.py"
